name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create Directories
      run: |
        mkdir -p "${CMAKE_SOURCE_DIR}/vcpkg/installed/x64-windows/share/glad"
        mkdir -p "${CMAKE_SOURCE_DIR}/vcpkg/installed/x64-windows/share/glfw3"

    - name: Clone glad
      run: git clone --depth=1 https://github.com/Dav1dde/glad.git "${CMAKE_SOURCE_DIR}/vcpkg/installed/x64-windows/share/glad"

    - name: Clone GLFW
      run: git clone --depth=1 https://github.com/glfw/glfw.git "${CMAKE_SOURCE_DIR}/vcpkg/installed/x64-windows/share/glfw3"

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
